### ISSUE TITLE
Recovered Badge is 0

### ISSUE THREAD

**Issue by codedawi** [fight-covid19/bagdes#1]
Unfortunately our main data provider has stoped tracking this information. However, the maintainer of coronavirus-tracker-api is potential working to find a new data provider (ExpDev07/coronavirus-tracker-api#161).

**Comment by warengonzaga** [comment]
How about this? https://github.com/NovelCOVID/API This is my data source for my open source project called [COVID-19 Tracker CLI](https://github.com/WarenGonzaga/covid19-tracker-cli)
